# Generated by Django 5.1 on 2024-11-25 17:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("especie", models.CharField(max_length=100)),
                ("raca", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Macho"), ("F", "Fêmea")], max_length=1
                    ),
                ),
                ("peso", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Dono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name="Endereco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logradouro", models.CharField(max_length=255)),
                ("numero", models.CharField(max_length=10)),
                ("complemento", models.CharField(blank=True, max_length=100)),
                ("bairro", models.CharField(max_length=100)),
                ("cidade", models.CharField(max_length=100)),
                ("uf", models.CharField(max_length=2)),
                (
                    "cep",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\d{5}-?\\d{3}$"
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Especialidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Procedimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("custo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duracao_estimativa", models.CharField(max_length=100)),
                ("necessidade_anestesia", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="CarteiraVacinacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_emissao", models.DateField()),
                ("vacinas", models.TextField()),
                ("observacoes", models.TextField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.animal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_documento", models.CharField(max_length=100)),
                ("data_emissao", models.DateField()),
                ("observacoes", models.TextField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.animal",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="animal",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="saude_animal.dono"
            ),
        ),
        migrations.CreateModel(
            name="Prontuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                ("observacoes", models.TextField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.animal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroSaude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_registro", models.DateTimeField(auto_now_add=True)),
                ("descricao", models.TextField()),
                (
                    "prontuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.prontuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "telefone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+?1?\\d{9,15}$"
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("senha", models.CharField(max_length=128)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Administrador", "Administrador"),
                            ("Veterinário", "Veterinário"),
                            ("Dono", "Dono"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("ultimo_acesso", models.DateTimeField(auto_now=True)),
                (
                    "endereco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.endereco",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dono",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="saude_animal.usuario"
            ),
        ),
        migrations.CreateModel(
            name="Veterinaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "telefone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^\\+?1?\\d{9,15}$"
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "endereco",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.endereco",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Veterinario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registro_crmv", models.CharField(max_length=20, unique=True)),
                (
                    "especialidade",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="saude_animal.especialidade",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veterinarios",
                        to="saude_animal.usuario",
                    ),
                ),
                (
                    "veterinaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="veterinarios",
                        to="saude_animal.veterinaria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vacina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_vacina", models.CharField(max_length=100)),
                ("data_vacinacao", models.DateField()),
                ("dose", models.CharField(max_length=100)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.animal",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.veterinario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TermoConsentimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_emissao", models.DateField()),
                ("observacoes", models.TextField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.animal",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.dono",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.veterinario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receituario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_emissao", models.DateField()),
                ("descricao_tratamento", models.TextField()),
                ("quantidade_prescrita", models.CharField(max_length=100)),
                ("via_administracao", models.CharField(max_length=100)),
                ("observacoes", models.TextField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.animal",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.dono",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.veterinario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FichaClinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_consulta", models.DateField()),
                ("historico", models.TextField()),
                ("anamnese", models.TextField()),
                ("queixas_principais", models.TextField()),
                ("queixas_secundarias", models.TextField()),
                ("exame_fisico", models.TextField()),
                ("suspeita_clinica", models.TextField()),
                ("diagnostico_diferencial", models.TextField()),
                ("exames_complementares", models.TextField()),
                ("tratamento_prescrito", models.TextField()),
                ("evolucao", models.TextField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.animal",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.dono",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.veterinario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_exame", models.CharField(max_length=100)),
                ("data_exame", models.DateField()),
                ("resultado", models.TextField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.animal",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.veterinario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cirurgia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_cirurgia", models.CharField(max_length=100)),
                ("data_cirurgia", models.DateField()),
                ("descricao", models.TextField()),
                ("resultado", models.TextField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.animal",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.veterinario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AtestadoSaude",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_emissao", models.DateField()),
                ("condicao_saude", models.TextField()),
                ("observacoes", models.TextField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.animal",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.veterinario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AtestadoObito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_obito", models.DateField()),
                ("hora_obito", models.TimeField()),
                ("provavel_causa_mortis", models.TextField()),
                ("idade", models.IntegerField()),
                ("orientacao_destinacao_corpo", models.TextField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.animal",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.dono",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.veterinario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alergia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.TextField()),
                ("data_diagnostico", models.DateField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.animal",
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.veterinario",
                    ),
                ),
            ],
        ),
    ]
