# Generated by Django 5.1 on 2024-09-02 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("raca", models.CharField(max_length=50)),
                ("idade", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Dono",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=100)),
                ("senha", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=20)),
                ("endereco", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Veterinaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("especialidade", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=20)),
                ("endereco", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("descricao", models.CharField(max_length=200)),
                ("resultado", models.CharField(max_length=200)),
                (
                    "id_animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.animal",
                    ),
                ),
                (
                    "id_veterinaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.veterinaria",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="animal",
            name="id_dono",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="saude_animal.dono"
            ),
        ),
        migrations.CreateModel(
            name="Exame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("data", models.DateField()),
                ("resultado", models.CharField(max_length=200)),
                (
                    "id_animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.animal",
                    ),
                ),
                (
                    "id_veterinaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.veterinaria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Monitoramento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batimentos", models.IntegerField()),
                ("temperatura", models.DecimalField(decimal_places=2, max_digits=5)),
                ("data", models.DateField()),
                (
                    "id_animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.animal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("mensagem", models.CharField(max_length=200)),
                ("data", models.DateField()),
                (
                    "id_dono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.dono",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prontuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observacao", models.TextField()),
                ("vacinas", models.TextField()),
                ("medicamentos", models.TextField()),
                (
                    "consultas",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.consulta",
                    ),
                ),
                (
                    "exames",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.exame",
                    ),
                ),
                (
                    "id_animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.animal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("arquivo", models.FileField(upload_to="arquivo")),
                (
                    "id_prontuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saude_animal.prontuario",
                    ),
                ),
            ],
        ),
    ]
