# Generated by Django 5.1 on 2024-09-01 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.TextField(verbose_name=200)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saude_animal.dono')),
            ],
        ),
        migrations.CreateModel(
            name='Monitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batimentos', models.IntegerField()),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data', models.DateField()),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saude_animal.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('mensagem', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('id_dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saude_animal.dono')),
            ],
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saude_animal.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('arquivo', models.FileField(upload_to='arquivo')),
                ('id_prontuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saude_animal.prontuario')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('resultado', models.CharField(max_length=200)),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saude_animal.animal')),
                ('id_veterinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saude_animal.veterinaria')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=200)),
                ('resultado', models.CharField(max_length=200)),
                ('id_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saude_animal.animal')),
                ('id_veterinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saude_animal.veterinaria')),
            ],
        ),
    ]
